name: 模组收录
description: 请求网站收录新模组。
title: "[Mod]: "
labels: ["类型:需求","状态:待处理","备注:模组"]
assignees:
  - QingFeng-awa
body:
  - type: markdown
    attributes:
      value: |
        # 感谢您愿意花费时间来提出issue。
        我们很高兴您能为“Among Us模组档案”提供反馈。
  - type: markdown
    attributes:
      value: |
        ## 在此之前,请您确认:
        - 这个模组没被收录。
        - 没有相同的模组已被请求收录
        - 您会准确、真实的填写下方内容。
        - 您了解[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)所讲述的内容。
  - type: checkboxes
    attributes:
      label: 请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: 我确认,这个模组没被收录。
          required: true
        - label: 我已经在[Issue Tracker](https://github.com/QingFeng-awa/AuModSite/issues)中找过我要提出的请求模组，没有找到相同请求的issue。
          required: true
        - label: 我已知晓,如果我不真实填写issue,则我的issue可能会被无条件关闭&锁定。
          required: true
  - type: input
    attributes:
      label: 请求收录的模组全称
      description: 注意,是**全称**而不是缩写。
    validations:
      required: true
  - type: input
    attributes:
      label: 与此模组相关的链接
      description: 可以是GitHub仓库链接,也可以是官方网站,亦或者是一个宣传视频。
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 其它信息
    validations:
      required: false
